In [1]:
#The aim of this project i sto clean the data set named movies.csv
#we'll clean the data set and use it for manipulations
#we'll also use the data for predictions and discovery of patterns
#Also after cleaning the data it will be used for visualizations
#Some of them will include graphs,countplots,scatters,heatmaps and many more

In [2]:
#import the necessary libraries

import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('/home/anonymous/datasets/movies.csv')

In [4]:
#print the first 50 rows

df.head(50)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
5,Outer Banks,(2020– ),"\nAction, Crime, Drama",7.6,\nA group of teenagers from the wrong side of ...,"\n \n Stars:\nChase Stokes, \nMa...","25,858",50.0,NaN
6,The Last Letter from Your Lover,(2021),"\nDrama, Romance",6.8,\nA pair of interwoven stories set in the past...,\n Director:\nAugustine Frizzell\n| \n S...,"5,283",110.0,NaN
7,Dexter,(2006–2013),"\nCrime, Drama, Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","\n \n Stars:\nMichael C. Hall, \...","665,387",53.0,NaN
8,Never Have I Ever,(2020– ),\nComedy,7.9,\nThe complicated life of a modern-day first g...,\n \n Stars:\nMaitreyi Ramakrish...,"34,530",30.0,NaN
9,Virgin River,(2019– ),"\nDrama, Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...",\n \n Stars:\nAlexandra Breckenr...,"27,279",44.0,NaN
10,Gunpowder Milkshake,(2021),"\nAction, Adventure, Thriller",6.0,\nThree generations of women fight back agains...,\n Director:\nNavot Papushado\n| \n Star...,"17,989",114.0,NaN
11,Lucifer,(2016–2021),"\nCrime, Drama, Fantasy",8.1,\nLucifer Morningstar has decided he's had eno...,"\n \n Stars:\nTom Ellis, \nLesle...","264,222",42.0,NaN
12,Fear Street: 1994,(2021),"\nDrama, Horror, Mystery",6.2,\nA circle of teenage friends accidentally enc...,\n Director:\nLeigh Janiak\n| \n Stars:\...,"50,148",107.0,NaN
13,Sex/Life,(2021– ),"\nComedy, Drama, Romance",5.4,\nA suburban mother of two takes a fantasy-cha...,"\n \n Stars:\nSarah Shahi, \nMik...","12,172",NaN,NaN
14,American Horror Story,(2011– ),"\nDrama, Horror, Thriller",8.0,\nAn anthology series centering on different c...,"\n \n Stars:\nLady Gaga, \nKathy...","286,488",60.0,NaN
15,Grey's Anatomy,(2005– ),"\nDrama, Romance",7.5,\nA drama centered on the personal and profess...,"\n \n Stars:\nEllen Pompeo, \nCh...","266,258",41.0,NaN
16,Breaking Bad,(2008–2013),"\nCrime, Drama, Thriller",9.4,\nA high school chemistry teacher diagnosed wi...,"\n \n Stars:\nBryan Cranston, \n...","1,552,311",49.0,NaN
17,The Good Doctor,(2017– ),\nDrama,8.1,"\nShaun Murphy, a young surgeon with autism an...","\n \n Stars:\nFreddie Highmore, ...","70,871",41.0,NaN
18,Atypical,(2017–2021),"\nComedy, Drama",8.3,"\nSam, an 18-year-old on the autism spectrum, ...",\n \n Stars:\nJennifer Jason Lei...,"71,544",30.0,NaN
19,Stranger Things,(2016– ),"\nDrama, Fantasy, Horror",8.7,"\nWhen a young boy disappears, his mother, a p...",\n \n Stars:\nMillie Bobby Brown...,"885,856",51.0,NaN
20,Fear Street: 1978,(2021),"\nDrama, Horror, Mystery",6.8,"\nShadyside, 1978. School's out for summer and...",\n Director:\nLeigh Janiak\n| \n Stars:\...,"36,634",109.0,NaN
21,Friends,(1994–2004),"\nComedy, Romance",8.9,\nFollows the personal and professional lives ...,"\n \n Stars:\nJennifer Aniston, ...","880,918",22.0,NaN
22,The Flash,(2014– ),"\nAction, Adventure, Drama",7.6,"\nAfter being struck by lightning, Barry Allen...","\n \n Stars:\nGrant Gustin, \nCa...","320,264",43.0,NaN
23,Peaky Blinders,(2013– ),"\nCrime, Drama",8.8,"\nA gangster family epic set in 1900s England,...","\n \n Stars:\nCillian Murphy, \n...","393,414",60.0,NaN
24,He-Man and the Masters of the Universe,(2021– ),"\nAnimation, Action, Adventure",NaN,\nEternia's Prince Adam discovers the power of...,\n,NaN,NaN,NaN
25,Chernobyl,(2021),"\nDrama, History, Romance",5.0,\nA story about a heroic fireman who worked as...,\n Director:\nDanila Kozlovskiy\n| \n St...,"4,681",136.0,NaN
26,Vikings,(2013–2020),"\nAction, Adventure, Drama",8.5,\nVikings transports us to the brutal and myst...,"\n \n Stars:\nKatheryn Winnick, ...","459,913",44.0,NaN
27,Better Call Saul,(2015– ),"\nCrime, Drama",8.8,\nThe trials and tribulations of criminal lawy...,"\n \n Stars:\nBob Odenkirk, \nRh...","347,857",46.0,NaN
28,Supernatural,(2005–2020),"\nDrama, Fantasy, Horror",8.4,\nTwo brothers follow their father's footsteps...,"\n \n Stars:\nJared Padalecki, \...","404,273",44.0,NaN
29,The Blacklist,(2013– ),"\nCrime, Drama, Mystery",8.0,"\nA new FBI profiler, Elizabeth Keen, has her ...","\n \n Stars:\nJames Spader, \nMe...","213,522",43.0,NaN
30,Fear Street: 1666,(2021),"\nHorror, Mystery",6.7,\nThe origins of Sarah Fier's curse are finall...,\n Director:\nLeigh Janiak\n| \n Stars:\...,"27,447",114.0,NaN
31,Animal Kingdom,(2016– ),"\nCrime, Drama",8.2,"\nCenters on a Southern California family, who...","\n \n Stars:\nShawn Hatosy, \nBe...","26,926",60.0,NaN
32,Brooklyn Nine-Nine,(2013–2022),"\nComedy, Crime",8.4,\nComedy series following the exploits of Det....,"\n \n Stars:\nAndy Samberg, \nSt...","248,583",22.0,NaN
33,NCIS: Naval Criminal Investigative Service,(2003– ),"\nAction, Crime, Drama",7.7,\nThe cases of the Naval Criminal Investigativ...,"\n \n Stars:\nMark Harmon, \nDav...","125,619",60.0,NaN
34,Kingdom,(2019– ),"\nAction, Drama, History",8.4,\nWhile strange rumors about their ill King gr...,"\n \n Stars:\nJu Ji-Hoon, \nBae ...","34,906",45.0,NaN
35,Modern Family,(2009–2020),"\nComedy, Drama, Romance",8.4,\nThree different but related families face tr...,"\n \n Stars:\nEd O'Neill, \nSofí...","378,030",22.0,NaN
36,Titans,(I) (2018– ),"\nAction, Adventure, Crime",7.7,\nA team of young superheroes combat evil and ...,"\n \n Stars:\nBrenton Thwaites, ...","73,656",45.0,NaN
37,The Witcher,(2019– ),"\nAction, Adventure, Fantasy",8.2,"\nGeralt of Rivia, a solitary monster hunter, ...","\n \n Stars:\nHenry Cavill, \nAn...","336,484",60.0,NaN
38,Downton Abbey,(2010–2015),"\nDrama, Romance",8.7,\nA chronicle of the lives of the British aris...,"\n \n Stars:\nHugh Bonneville, \...","171,804",58.0,NaN
39,Shingeki no kyojin,(2013–2022),"\nAnimation, Action, Adventure",9.0,\nAfter his hometown is destroyed and his moth...,"\n \n Stars:\nYûki Kaji, \nMarin...","242,582",24.0,NaN
40,Suits,(2011–2019),"\nComedy, Drama",8.4,"\nOn the run from a drug deal gone bad, brilli...","\n \n Stars:\nGabriel Macht, \nP...","374,263",44.0,NaN
41,La casa de papel,(2017–2021),"\nAction, Crime, Mystery",8.3,\nAn unusual group of robbers attempt to carry...,"\n \n Stars:\nÚrsula Corberó, \n...","341,858",70.0,NaN
42,Schitt's Creek,(2015–2020),\nComedy,8.5,\nWhen rich video-store magnate Johnny Rose an...,"\n \n Stars:\nEugene Levy, \nCat...","90,728",22.0,NaN
43,Outlander,(2014– ),"\nDrama, Fantasy, Romance",8.4,\nAn English combat nurse from 1945 is mysteri...,"\n \n Stars:\nCaitriona Balfe, \...","134,991",64.0,NaN
44,The Last Kingdom,(2015– ),"\nAction, Drama, History",8.4,\nAs Alfred the Great defends his kingdom from...,"\n \n Stars:\nAlexander Dreymon,...","94,650",60.0,NaN
45,Black Mirror,(2011– ),"\nDrama, Sci-Fi, Thriller",8.8,"\nAn anthology series exploring a twisted, hig...","\n \n Stars:\nDaniel Lapaine, \n...","469,407",60.0,NaN
46,Ozark,(2017– ),"\nCrime, Drama, Thriller",8.4,\nA financial advisor drags his family from Ch...,"\n \n Stars:\nJason Bateman, \nL...","206,090",60.0,NaN
47,The Crown,(2016– ),"\nBiography, Drama, History",8.6,\nFollows the political rivalries and romance ...,"\n \n Stars:\nClaire Foy, \nOliv...","169,517",58.0,NaN
48,Sweet Tooth,(2021– ),"\nAction, Adventure, Drama",7.9,\nA boy who is half human and half deer surviv...,"\n \n Stars:\nNonso Anozie, \nCh...","37,142",NaN,NaN
49,Army of the Dead,(2021),"\nAction, Crime, Horror",5.8,"\nFollowing a zombie outbreak in Las Vegas, a ...",\n Director:\nZack Snyder\n| \n Stars:\n...,"132,378",148.0,NaN

In [5]:
#insert a random column called No_ofViews

No_ofViews=np.random.randint(1000000,size=len(df))
df.insert(1,'No_ofViews',No_ofViews)
df

,MOVIES,No_ofViews,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,846567,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,202550,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,879165,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,557197,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,852029,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,505181,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,542257,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,73091,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,726133,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,760538,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [6]:
#Get to know the description of the dataset

df.describe()

          No_ofViews       RATING      RunTime
count    9999.000000  8179.000000  7041.000000
mean   504022.232923     6.921176    68.688539
std    289160.209689     1.220232    47.258056
min        32.000000     1.100000     1.000000
25%    254591.000000     6.200000    36.000000
50%    505608.000000     7.100000    60.000000
75%    753957.500000     7.800000    95.000000
max    999935.000000     9.900000   853.000000

In [7]:
#Renaming of colummns

df=df.rename(columns={"MOVIES":"Movies","YEAR":"Year","GENRE":"Genre","RATING":"Rating","ONE-LINE":"One_line","STARS":"Stars","VOTES":"Votes"})

In [8]:
df

,Movies,No_ofViews,Year,Genre,Rating,One_line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,846567,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,202550,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,879165,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,557197,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,852029,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,505181,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,542257,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,73091,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,726133,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,760538,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [9]:
#description after renaming columns

df.describe()

          No_ofViews       Rating      RunTime
count    9999.000000  8179.000000  7041.000000
mean   504022.232923     6.921176    68.688539
std    289160.209689     1.220232    47.258056
min        32.000000     1.100000     1.000000
25%    254591.000000     6.200000    36.000000
50%    505608.000000     7.100000    60.000000
75%    753957.500000     7.800000    95.000000
max    999935.000000     9.900000   853.000000

In [10]:
#slicing the first 4 rows of the first 3 columns in the dataset

df.iloc[:4,0:3]

                                Movies  No_ofViews         Year
0                        Blood Red Sky      846567       (2021)
1  Masters of the Universe: Revelation      202550     (2021– )
2                     The Walking Dead      879165  (2010–2022)
3                       Rick and Morty      557197     (2013– )

In [11]:
df.Rating.mean()

6.921176182907419

In [12]:
#replacing the null values in the Rating column with a float

df.Rating.fillna(6.921176,inplace=True)

In [13]:
df.Rating

0       6.100000
1       5.000000
2       8.200000
3       9.200000
4       6.921176
          ...
9994    6.921176
9995    6.921176
9996    6.921176
9997    6.921176
9998    6.921176
Name: Rating, Length: 9999, dtype: float64

In [14]:
#displaying the dataset to confirm that the null values have been replaced

df

,Movies,No_ofViews,Year,Genre,Rating,One_line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,846567,(2021),"\nAction, Horror, Thriller",6.100000,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,202550,(2021– ),"\nAnimation, Action, Adventure",5.000000,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,879165,(2010–2022),"\nDrama, Horror, Thriller",8.200000,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,557197,(2013– ),"\nAnimation, Adventure, Comedy",9.200000,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,852029,(2021),"\nAction, Crime, Horror",6.921176,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,505181,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,542257,(2021– ),"\nAnimation, Action, Adventure",6.921176,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,73091,(2022– ),"\nDocumentary, Sport",6.921176,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,726133,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,760538,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

In [15]:
#replacing the null values in the RunTime column with the mean of the column

df.RunTime.fillna(68.688539,inplace=True)
df

,Movies,No_ofViews,Year,Genre,Rating,One_line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,846567,(2021),"\nAction, Horror, Thriller",6.100000,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.000000,NaN
1,Masters of the Universe: Revelation,202550,(2021– ),"\nAnimation, Action, Adventure",5.000000,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.000000,NaN
2,The Walking Dead,879165,(2010–2022),"\nDrama, Horror, Thriller",8.200000,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.000000,NaN
3,Rick and Morty,557197,(2013– ),"\nAnimation, Adventure, Comedy",9.200000,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.000000,NaN
4,Army of Thieves,852029,(2021),"\nAction, Crime, Horror",6.921176,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,68.688539,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,505181,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,68.688539,NaN
9995,Arcane,542257,(2021– ),"\nAnimation, Action, Adventure",6.921176,\nAdd a Plot\n,\n,NaN,68.688539,NaN
9996,Heart of Invictus,73091,(2022– ),"\nDocumentary, Sport",6.921176,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,68.688539,NaN
9997,The Imperfects,726133,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,68.688539,NaN
9998,The Imperfects,760538,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,68.688539,NaN

In [16]:
df.RunTime.mean()

68.68853869006762

In [17]:
x=df.iloc[:4,7]
print(x)

0     21,062
1     17,870
2    885,805
3    414,849
Name: Votes, dtype: object

In [18]:
x = x.str.replace(",", "")
x = pd.to_numeric(x)

In [19]:
x.mean()

334896.5

In [20]:
df.Votes.fillna(x.mean(),inplace=True)

In [21]:
df

,Movies,No_ofViews,Year,Genre,Rating,One_line,Stars,Votes,RunTime,Gross
0,Blood Red Sky,846567,(2021),"\nAction, Horror, Thriller",6.100000,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.000000,NaN
1,Masters of the Universe: Revelation,202550,(2021– ),"\nAnimation, Action, Adventure",5.000000,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.000000,NaN
2,The Walking Dead,879165,(2010–2022),"\nDrama, Horror, Thriller",8.200000,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.000000,NaN
3,Rick and Morty,557197,(2013– ),"\nAnimation, Adventure, Comedy",9.200000,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.000000,NaN
4,Army of Thieves,852029,(2021),"\nAction, Crime, Horror",6.921176,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,334896.5,68.688539,NaN
...,...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,505181,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,334896.5,68.688539,NaN
9995,Arcane,542257,(2021– ),"\nAnimation, Action, Adventure",6.921176,\nAdd a Plot\n,\n,334896.5,68.688539,NaN
9996,Heart of Invictus,73091,(2022– ),"\nDocumentary, Sport",6.921176,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,334896.5,68.688539,NaN
9997,The Imperfects,726133,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,334896.5,68.688539,NaN
9998,The Imperfects,760538,(2021– ),"\nAdventure, Drama, Fantasy",6.921176,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,334896.5,68.688539,NaN

In [22]:
df.describe()

          No_ofViews       Rating      RunTime
count    9999.000000  9999.000000  9999.000000
mean   504022.232923     6.921176    68.688539
std    289160.209689     1.103594    39.655700
min        32.000000     1.100000     1.000000
25%    254591.000000     6.500000    45.000000
50%    505608.000000     6.921176    68.688539
75%    753957.500000     7.600000    86.000000
max    999935.000000     9.900000   853.000000

In [ ]:
#replacing the NaN in the Gross column with a string "unknown"

df.Gross.fillna("unknown",inplace=True)

In [ ]:
df

In [ ]:
#Displaying the first 50 row of the dataset to confirm the changes

df.head(50)

In [ ]:
#Displaying the clean version of the dataset

df

In [ ]:
df.Votes=df.Votes.str.replace(",","")
df.Votes=pd.to_numeric(df.Votes)

In [ ]:
plt.figure(figsize=(16,6))
plt.title("Movies distribution")
sns.lineplot(data=df['No_ofViews'], label="No_ofViews")
sns.lineplot(data=df['Votes'], label="Votes")

In [ ]:
df.groupby('Movies').RunTime.agg([len,min,max])

In [ ]:
w=0.025
y=9999
z=w*y
print(z)

In [ ]:
df[['RunTime','Rating']].sample(frac=0.025)

In [ ]:
sns.lineplot(df[['RunTime','Rating']].sample(frac=0.025))

In [ ]:
sns.barplot(df[['RunTime','Rating']].sample(frac=0.025))

In [ ]:
#saving the cleaned dataset to have a clean version
df.to_csv('movies_cleaned.csv', index=False)